apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-data-db
  labels:
    app: my-app
    type: mdatabase
spec:
  template:
    metadata:
      labels:
        app:  my-app
        type: mongo-db
    spec:
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-volume-claim
      containers:
      - name: mongo-db
        image: mongo:4.4.3
        ports:
        - containerPort: 27017
        volumeMounts:
          - mountPath: '/data/db'
            name: mongo-storage

  replicas: 1
  selector:
    matchLabels:
      app:  my-app
      type: mongo-db
