apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume
  labels:
    type: mongo-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: normal
  hostPath:
    path: '/data/db'
