
kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-react-app
  labels:
    app: my-react-app
    type: my-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-react-app
      type: my-front

  template:
    metadata:
      labels:
        app: my-react-app
        type: my-front
    spec:
      containers:
        - name: my-react-app
          image: docker.io/70461e8943d9/web-app
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: my-react-app
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: my-react-app
    type: my-front
