image: node

stages:
    - build
    - deploy
build:
    stage: build

    script:
        - echo "Building deploy package"
        - yarn install
        - yarn build
        - echo "Build successful"
    artifacts:
        expire_in: 1 hour
        paths:
            - build
deploy_production:
    stage: deploy
    environment:
        name: production
        url: example.com
    script:
        - echo "Deploying to server"
        - cp -r -force build/* $DEPLOY_SERVER_PATH
        - echo "Deployed"
